### ISSUE TITLE
Backend gyárt Open API Json kimenetet az API-ból

### ISSUE THREAD

**Issue by borazslo** [joladnijo/joladnijo-backend#31]

**Comment by nvi9** [comment]
Elég, ha lekérhető az aktuális séma a backendtől, vagy kellene ReDoc (vagy Swagger) UI is hozzá?

**Comment by VFiber** [comment]
Sziasztok,
közben a Slack-os megbeszélés alapján az alábbira jutottunk, ezt kérnénk tőletek:

Nem szükséges az UI része, az OpenAPI json amire szükségünk van, abból tudunk dolgozni.

A misu által generált verzió teljesen jó, ha van lehetőség ennek egy endpointon való kihelyezésére, az jelentősen megkönnyítené az FE oldalakon a változtatások lekövetését.

misu az alábbit írta a Slack-re:
`Feltettem az uritemplate lib-et, futtattam egy ./manage.py generateschema --format openapi-json --file openapi-schema.json parancsot, és ezt kaptam. Mennyire közelíti meg az elvárásokat?
`
Illetve Ruppert Balázsnak volt egy kommentje, hogy ez megoldható dinamikusan is.

Ennek nem feltétlen kellene dinamikusnak lennie (főleg ha jelentős erőforrásokat követel egy ilyen lekérése a BE-től), egyszerű statikus fájlként ha előáll a build folyamat során és ez elérhető az API egy endpointján vagy máshol, az teljesen jól működhet.
