### ISSUE TITLE
Elek Laci tudjon bármilyen módon adatokat be tudjon vinni

### ISSUE THREAD

**Issue by borazslo** [joladnijo/joladnijo-backend#40]
Mert MVP-ben még nem lesznek userek.

**Comment by borazslo** [comment]
MVP-ig nem cél a rendes backoffice elkészülése. Ezért fogjuk használni a django default admin világot. Csak majd mutassátok meg nekem majd légyszi.

**Comment by SzNagyMisu** [comment]
Illetve valószínűleg ez @molnarbence vagy @Saboteur777 feladata lesz, hogy a fenti kódot lefuttassák prod környezetben, és a felhasználónév-email párost kommunikálják @borazslo felé.

**Comment by molnarbence** [comment]
@SzNagyMisu vagy egy olyan buildet keszitunk, amelyik csak ezt futtatja. A felhasznalonevet es jelszot mi adjuk meg, vagy a `createsuperpuser` parancs kidobja a jelszot a logokba?

**Comment by molnarbence** [comment]
Megneztem, hogy kell a `createsuperuser`-t futtatni, csak elotte ezt: https://github.com/joladnijo/joladnijo-backend/pull/44 kene approvolni, mert ezutan ujra kell krealni az adatbazist stagingben es live-on.

**Comment by borazslo** [comment]
Hol tartunk ezzel? Stagingen tudok valahogy adatokat mókolni?

**Comment by nvi9** [comment]
> Hol tartunk ezzel? Stagingen tudok valahogy adatokat mókolni?

#36 befejezése után lenne érdemes szerintem

**Comment by borazslo** [comment]
#36 befejezve és köszönöm, hogy működik ez is. Staging-en van nevem jelszavam és nyomkodom is. (Kis hibája még a lokális futtatáshoz képest, hogy a css styling nem üzemel, de sebaj.)
