### ISSUE TITLE
A backend visszaadja egy Slug alapján az AidCenter adatait

### ISSUE THREAD

**Issue by SzNagyMisu** [joladnijo/joladnijo-backend#6]
## Feladat

> Verb: GET
> Path: /aid-centers/{slug}

### Response struktúra

```
{
  id, name, slug, photo,
  organization: {
    id, name, logo, slug, note, contact: {
      name, phone, email, facebook, url, note
    },
    editableByCurrentUser
  },
  address: {
    countryCode, postalCode, city, address, note
  },
  geoLocation: {
    lat, lon
  },
  contact: {
    name, phone, email, facebook, url, note
  },
  callRequired: required | suggested | none | denied,
  assetsRequested: [
    {
      id, name, assetCategory, icon, note, urgent
    }
  ],
  assetsFulfilled: [ < mint fentebb > ],
  assetsOverloaded: [ < mint fentebb > ],
  note, moneyAccepted: boolean, moneyDescription, campaignEndingOn, campaignEnded: boolean, editableByCurrentUser,
  feed: [
    id, date, event, urgent: boolean, icon, category, name, note
  ]
}
```

### Szükséges táblák

A következő alap oszlopok minden táblának részét képezik:

```
id*: char(36) unique primary key (GUID)
created_at: timestamp
updated_at: timestamp
created_by: foreign key a users táblához (valószínűleg csak MVP után)
updated_by: foreign key a users táblához (valószínűleg csak MVP után)
```

* validálást ne felejtsük
* az `enum` típusú mezőket az adatbázisban varchar-ként tárolnám, és django szinten biztosítanám az enum-ságot
* a `note` mezőket első körben 255 max hosszúságúra írtam, de lehet, hogy emelhetjük pl 1023-ra

#### organizations

```
name*: varchar(255) unique
slug*: varchar(255) unique
note: varchar(255)
```

#### aid_centers

```
name*: varchar(255) unique
photo: varchar(255) - relative útvonal a(z első körben kézzel feltöltött) képhez
slug*: varchar(255) unique
organization*: foreign key
geo_location: point
call_required: varchar(20)
note: varchar(255)
money_accepted: boolean
money_description: varchar(1023)
campaign_ending_on: timestamp
```

#### asset_requests

```
name*: varchar(255)
category*: varchar(255)
icon: varchar(50)
note: varchar(255)
urgent: boolean
status*: varchar(20)
```

#### contacts

```
organization*: foreign key
aid_center: foreign key (1:1, nullable)
name*: varchar(255)
phone: varchar(20)
email*: varchar(255)
facebook: varchar(255)
url: varchar(255)
note: varchar(255)
```

#### addresses

```
aid_center: foreign key (1:1)
country_code: varchar(3)
postal_code: varchar(10)
city: varchar(50)
address: varchar(100)
note: varchar(255)
```

#### feeds

```
name*: varchar(255)
category*: varchar(255)
icon: varchar(50)
note: varchar(255)
urgent: boolean
status*: varchar(20)
event*: varchar(20)
```

**Comment by borazslo** [comment]
Megpróbálhatjuk az asset_requestsből kinyerni, de akkor oda kell még mindenféle mező. Mert a feed-be benne kell legyen, hogy három nappal ezelőtt átkerült az assetsRequested-ből assetFullfiled-be pl. És aztán tegnap vissza. Szóval azért van itt tárolni való

**Comment by SzNagyMisu** [comment]
Update-eltem

**Comment by molnarm** [comment]
A #13, #14 miben más, mint ez?

**Comment by borazslo** [comment]
Semmiben. Egyszerűen ez az issue korábban jött létre de nem volt a
projektben így nem tűnt fel és létre hoztam a többit. Igyekszem szépen
bekommentalni és lezárni a felesleget.

Márton Molnár ***@***.***> ezt írta (időpont: 2022. márc.
11., P 9:04):

**Comment by nvi9** [comment]
A változások követésére használhatnánk [ezt](https://django-simple-history.readthedocs.io), mit gondoltok? Lehet, hogy a `feeds` táblát is kiválthatja valamilyen szinten.

**Comment by nvi9** [comment]
> Az `asset_requests`-be nem kéne egy általános `id`, de leginkább egy `aid_center_id` foreign key?

De, a PR-ban már van FK.

**Comment by borazslo** [comment]
Téényleg. No, akkor egy jogos emberke hagyja jóvá a PR-t mert jóóóóó sok  minden van benne. Aztán majd sok-kicsi javítással tovább helyre rakjuk csak addig is hadd szóljon
